import React, { useState, useEffect } from 'react';
import { BrainCircuit, TrendingDown, AlertTriangle, Loader2 } from 'lucide-react';
import api from '../api';

const AiPredictionSidebar = ({ refreshTrigger }) => {
  const [predictionData, setPredictionData] = useState({
    prediction: [],
    recommendations: []
  });
  const [loading, setLoading] = useState(true);

  const fetchPrediction = async () => {
    setLoading(true);
    try {
      const response = await api.get('/prediction');
      if (response.data && response.data.status === 'success') {
        setPredictionData({
          prediction: response.data.data.prediction || [],
          recommendations: response.data.data.recommendations || []
        });
      }
    } catch (error) {
      console.error("Failed to fetch AI prediction:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPrediction();
  }, [refreshTrigger]);
  return (
    <div className="glass-card" style={{ 
      width: '320px', 
      padding: '1.5rem',
      display: 'flex',
      flexDirection: 'column',
      gap: '1.5rem',
      background: 'linear-gradient(to bottom, var(--bg-card), var(--primary-teal-light))'
    }}>
      
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', paddingBottom: '1rem', borderBottom: '1px solid var(--border-light)' }}>
        <div style={{ background: 'var(--primary-teal)', padding: '0.5rem', borderRadius: '0.5rem', color: 'white' }}>
          <BrainCircuit size={24} />
        </div>
        <h2 style={{ fontSize: '1.25rem', fontWeight: '600', color: 'var(--text-main)' }}>
          AI Resource Prediction
        </h2>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <h3 style={{ fontSize: '0.875rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Prediction
        </h3>
        
        <div style={{ background: 'white', padding: '1rem', borderRadius: 'var(--radius-md)', borderLeft: '4px solid var(--accent-orange)', minHeight: '80px' }}>
          {loading ? (
             <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%', color: 'var(--text-muted)' }}>
               <Loader2 className="animate-spin" size={20} />
             </div>
          ) : predictionData.prediction.length > 0 ? (
            <ul style={{ margin: 0, paddingLeft: '1.2rem', color: 'var(--text-main)', fontSize: '0.9rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              {predictionData.prediction.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          ) : (
            <div style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>No current predictions.</div>
          )}
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginTop: '1rem' }}>
        <h3 style={{ fontSize: '0.875rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Recommendations
        </h3>
        
        <div style={{ background: 'white', padding: '1rem', borderRadius: 'var(--radius-md)', borderLeft: '4px solid var(--accent-red)', minHeight: '100px' }}>
           {loading ? (
             <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%', color: 'var(--text-muted)' }}>
               <Loader2 className="animate-spin" size={20} />
             </div>
          ) : predictionData.recommendations.length > 0 ? (
            <ul style={{ margin: 0, paddingLeft: '1.2rem', color: 'var(--text-main)', fontSize: '0.9rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              {predictionData.recommendations.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          ) : (
             <div style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>No current recommendations.</div>
          )}
        </div>
      </div>

      <div style={{ 
        marginTop: 'auto', 
        fontSize: '0.75rem', 
        color: 'var(--text-muted)', 
        display: 'flex', 
        alignItems: 'center', 
        gap: '0.5rem',
        justifyContent: 'center',
        paddingTop: '1rem',
        borderTop: '1px solid var(--border-light)'
      }}>
        <AlertTriangle size={14} />
        <span>Predictions generated by AI model v2.1</span>
      </div>

    </div>
  );
};

export default AiPredictionSidebar;
